<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock Audit Trail</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* Header/Footer */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        /* Meta Box */
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        /* Data Table */
        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        /* Specific Indicators */
        .type-in { color: #15803d; font-weight: bold; } /* Green */
        .type-out { color: #b91c1c; font-weight: bold; } /* Red */

        .stock-change { font-family: monospace; font-size: 8px; color: #555; }
        .arrow { font-size: 10px; color: #999; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">123 Industrial Area, Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>Audit Trail Log</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: AUDIT-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL AUDIT DOCUMENT</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="right"><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="12%">Date / Time</th>
                    <th width="15%">Store</th>
                    <th width="20%">Product</th>
                    <th width="5%">Type</th>
                    <th width="12%">Reason</th>
                    <th width="8%" style="text-align: right;">Qty</th>
                    <th width="13%" style="text-align: center;">Stock Impact</th>
                    <th width="15%">User</th>
                </tr>
            </thead>
            <tbody>
                @foreach($adjustments as $adj)
                    <tr>
                        <td>{{ $adj->created_at->format('d M Y, H:i') }}</td>
                        <td>{{ $adj->store->name ?? '—' }}</td>
                        <td>
                            <strong>{{ $adj->product->name ?? '—' }}</strong><br>
                            <span style="font-size:8px; color:#666;">{{ $adj->product->sku ?? '' }}</span>
                        </td>
                        <td>
                            @if($adj->type === 'in')
                                <span class="type-in">IN (+)</span>
                            @else
                                <span class="type-out">OUT (-)</span>
                            @endif
                        </td>
                        <td>{{ $adj->adjustmentReason->name ?? '—' }}</td>

                        <td align="right" style="font-weight:bold;">
                            {{ number_format($adj->quantity) }}
                        </td>

                        <td align="center" class="stock-change">
                            {{ number_format($adj->old_stock) }}
                            <span class="arrow">&rarr;</span>
                            <strong>{{ number_format($adj->new_stock) }}</strong>
                        </td>

                        <td>{{ $adj->user->name ?? 'System' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Records:</strong> {{ count($adjustments) }}
        </div>
    </main>
</body>
</html>
