<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Order Report</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* Header & Footer Fixed Positioning */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        /* Typography & Layout */
        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        /* 🟢 NEW: Stat Cards CSS */
        .stats-table { width: 100%; border-spacing: 10px; margin-bottom: 15px; margin-left: -5px; }
        .stat-box { padding: 10px; border-radius: 4px; border: 1px solid #ddd; text-align: center; }

        .stat-gray  { background: #f9fafb; border-color: #e5e7eb; }
        .stat-blue  { background: #eff6ff; border-color: #bfdbfe; }
        .stat-green { background: #f0fdf4; border-color: #bbf7d0; }

        .stat-label { font-size: 8px; text-transform: uppercase; letter-spacing: 0.5px; color: #6b7280; }
        .stat-value { font-size: 16px; font-weight: bold; margin-top: 4px; color: #111827; }
        .stat-sub   { font-size: 8px; margin-top: 2px; color: #9ca3af; }

        /* Info Box */
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        /* Table Styling */
        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        /* Status & Highlights */
        .ref-cell { font-family: monospace; font-weight: bold; color: #2d3748; }
        .status-ordered { color: #1e40af; font-weight: bold; }
        .status-received { color: #15803d; font-weight: bold; }
        .status-draft { color: #6b7280; font-style: italic; }
        .status-cancelled { color: #991b1b; }

        .amt-cell { font-weight: bold; color: #ea580c; text-align: right; }
        .text-right { text-align: right; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">123 Industrial Area, Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>Purchase Order Report</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: PO-REPORT-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">INTERNAL USE ONLY</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="center">
                         <strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}
                    </td>
                    <td align="right"><strong>Records:</strong> {{ $purchaseOrders->count() }}</td>
                </tr>
            </table>
        </div>

        {{-- 🟢 NEW: Executive Summary Cards (Mirrors Dashboard) --}}
        <table class="stats-table">
            <tr>
                {{-- Card 1: Drafts --}}
                <td width="33%">
                    <div class="stat-box stat-gray">
                        <div class="stat-label">Draft Orders</div>
                        <div class="stat-value">{{ $purchaseOrders->where('status', 'draft')->count() }}</div>
                        <div class="stat-sub">Waiting Approval</div>
                    </div>
                </td>

                {{-- Card 2: Pending (Ordered/Partial) + Value --}}
                <td width="33%">
                    <div class="stat-box stat-blue">
                        <div class="stat-label" style="color: #1e40af;">Pending Arrival</div>
                        <div class="stat-value" style="color: #1e3a8a;">
                            {{ $purchaseOrders->whereIn('status', ['ordered', 'partial'])->count() }}
                        </div>
                        <div class="stat-sub" style="color: #3b82f6;">
                            Value: {{ number_format($purchaseOrders->whereIn('status', ['ordered', 'partial'])->sum('total_amount')) }}
                        </div>
                    </div>
                </td>

                {{-- Card 3: Completed --}}
                <td width="33%">
                    <div class="stat-box stat-green">
                        <div class="stat-label" style="color: #166534;">Completed</div>
                        <div class="stat-value" style="color: #14532d;">
                            {{ $purchaseOrders->where('status', 'received')->count() }}
                        </div>
                        <div class="stat-sub" style="color: #22c55e;">Fully Received</div>
                    </div>
                </td>
            </tr>
        </table>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="12%">Order Date</th>
                    <th width="15%">PO Number</th>
                    <th width="10%">Status</th>
                    <th width="20%">Supplier</th>
                    <th width="15%">Destination Store</th>
                    <th width="13%">Requested By</th>
                    <th width="15%" class="text-right">Total Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($purchaseOrders as $po)
                    <tr>
                        <td>{{ $po->order_date ? $po->order_date->format('d M Y') : '-' }}</td>
                        <td class="ref-cell">{{ $po->po_number }}</td>
                        <td>
                            @php $status = $po->status; @endphp
                            @if($status === 'ordered') <span class="status-ordered">ORDERED</span>
                            @elseif($status === 'received') <span class="status-received">RCVD</span>
                            @elseif($status === 'cancelled') <span class="status-cancelled">CNCL</span>
                            @else <span class="status-draft">{{ strtoupper($status) }}</span> @endif
                        </td>
                        <td>{{ $po->supplier->name ?? 'N/A' }}</td>
                        <td>{{ $po->store->name ?? 'N/A' }}</td>
                        <td>{{ $po->requestedBy->name ?? 'System' }}</td>
                        <td class="amt-cell">{{ number_format($po->total_amount, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="text-right font-bold" style="padding: 8px;">TOTAL VALUE</td>
                    <td class="amt-cell" style="background: #fff; font-size: 11px; border-top: 2px solid #ea580c;">
                        {{ number_format($purchaseOrders->sum('total_amount'), 2) }}
                    </td>
                </tr>
            </tfoot>
        </table>

        <div style="margin-top: 20px; text-align: left; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <em>Note: All currency values are in KES unless otherwise stated.</em>
        </div>
    </main>
</body>
</html>
