<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Report</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        .sku-cell { font-family: monospace; font-weight: bold; color: #2d3748; }

        /* Status Indicators */
        .status-low { color: #b91c1c; font-weight: bold; font-size: 8px; }
        .status-ok { color: #15803d; font-weight: bold; font-size: 8px; }
        .row-low-stock { background-color: #fef2f2 !important; } /* Light red bg for low stock rows */

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">123 Industrial Area, Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>Inventory Report</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: INV-EXP-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="right"><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="15%">Store</th>
                    <th width="30%">Product</th>
                    <th width="15%">SKU</th>
                    <th width="10%" style="text-align: right;">On Hand</th>
                    <th width="10%" style="text-align: right;">Reorder Lvl</th>
                    <th width="15%">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($stocks as $s)
                    @php
                        $isLow = $s->reorder_level > 0 && $s->current_stock <= $s->reorder_level;
                    @endphp
                    <tr class="{{ $isLow ? 'row-low-stock' : '' }}">
                        <td align="center">{{ $loop->iteration }}</td>
                        <td>{{ $s->store->name ?? '—' }}</td>
                        <td><strong>{{ $s->product->name ?? '—' }}</strong></td>
                        <td class="sku-cell">{{ $s->product->sku ?? '—' }}</td>

                        <td align="right" style="font-weight: bold;">
                            {{ number_format($s->current_stock) }}
                        </td>

                        <td align="right" style="color: #666;">
                            {{ $s->reorder_level > 0 ? number_format($s->reorder_level) : '-' }}
                        </td>

                        <td>
                            @if($isLow)
                                <span class="status-low">⚠️ LOW STOCK</span>
                            @else
                                <span class="status-ok">✔ GOOD</span>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Items Listed:</strong> {{ count($stocks) }} &nbsp;|&nbsp;
            <strong>Total Volume:</strong> {{ number_format($stocks->sum('current_stock')) }} Units
        </div>
    </main>
</body>
</html>
