<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock Card: {{ $stock->product->sku }}</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 10px; color: #333; line-height: 1.5; }

        /* Header/Footer */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        /* Layout */
        .header-table, .meta-table, .info-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        .meta-table td { vertical-align: top; }
        .info-table th { background: #f8fafc; color: #4a5568; padding: 6px; text-align: left; border: 1px solid #e2e8f0; font-size: 9px; }
        .info-table td { padding: 6px; border: 1px solid #e2e8f0; font-size: 10px; }

        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }
        .section-title { font-size: 11px; font-weight: bold; color: #ea580c; border-bottom: 1px solid #e2e8f0; margin: 20px 0 10px 0; text-transform: uppercase; }

        /* Big Numbers */
        .big-stat { font-size: 24px; font-weight: bold; color: #2d3748; }
        .stat-label { font-size: 9px; color: #777; text-transform: uppercase; }

        /* Status Colors */
        .status-ok { color: #15803d; font-weight: bold; }
        .status-low { color: #b91c1c; font-weight: bold; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">
                        123 Industrial Area, Enterprise Road<br>
                        Nairobi, Kenya 00100
                    </div>
                </td>
                <td width="40%" align="right">
                    <h1>Inventory Card</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">
                        SKU: {{ $stock->product->sku }}
                    </div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL DOCUMENT</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div style="background: #fff7ed; border: 1px solid #fed7aa; padding: 10px; margin-bottom: 20px; font-size: 9px;">
            <table class="meta-table">
                <tr>
                    <td width="33%"><strong>Generated By:</strong><br> {{ auth()->user()->name ?? 'System User' }}</td>
                    <td width="33%"><strong>Store:</strong><br> {{ $stock->store->name }}</td>
                    <td width="33%" align="right"><strong>Date:</strong><br> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <div class="section-title">Product Identity</div>
        <table class="info-table">
            <tr>
                <th width="25%">Product Name</th>
                <td><strong>{{ $stock->product->name }}</strong></td>
            </tr>
            <tr>
                <th>SKU</th>
                <td style="font-family: monospace;">{{ $stock->product->sku }}</td>
            </tr>
            <tr>
                <th>Location / Store</th>
                <td>{{ $stock->store->name }} <span style="color:#777">({{ $stock->store->code ?? 'N/A' }})</span></td>
            </tr>
        </table>

        <div class="section-title">Inventory Status</div>
        <table width="100%" style="margin-bottom: 20px;">
            <tr>
                <td width="33%" align="center" style="border: 1px solid #eee; padding: 15px;">
                    <div class="stat-label">Current On Hand</div>
                    <div class="big-stat">{{ number_format($stock->current_stock) }}</div>
                </td>
                <td width="33%" align="center" style="border: 1px solid #eee; padding: 15px;">
                    <div class="stat-label">Stock Status</div>
                    <div style="font-size: 16px; margin-top: 5px;">
                        @if($stock->reorder_level > 0 && $stock->current_stock <= $stock->reorder_level)
                            <span class="status-low">⚠️ LOW STOCK</span>
                        @else
                            <span class="status-ok">✔ ADEQUATE</span>
                        @endif
                    </div>
                </td>
                <td width="33%" align="center" style="border: 1px solid #eee; padding: 15px;">
                    <div class="stat-label">Last Updated</div>
                    <div style="font-size: 14px; font-weight: bold; margin-top: 8px;">
                        {{ $stock->updated_at->format('d M Y') }}
                    </div>
                </td>
            </tr>
        </table>

        <div class="section-title">Reorder Policy</div>
        <table class="info-table">
            <tr>
                <th width="30%">Reorder Level (Threshold)</th>
                <td>
                    @if($stock->reorder_level > 0)
                        {{ number_format($stock->reorder_level) }} Units
                    @else
                        <span style="color:#999; font-style: italic;">Not Set</span>
                    @endif
                </td>
            </tr>
            <tr>
                <th>Restock Quantity</th>
                <td>
                    @if($stock->reorder_quantity > 0)
                        {{ number_format($stock->reorder_quantity) }} Units
                    @else
                        <span style="color:#999; font-style: italic;">Not Set</span>
                    @endif
                </td>
            </tr>
        </table>

    </main>
</body>
</html>
