<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>PO Items Report</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }
        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }

        /* Stats Table for PDF */
        .stats-table { width: 100%; border-spacing: 10px; margin-bottom: 15px; }
        .stat-box { padding: 8px; border: 1px solid #ddd; text-align: center; background: #f9fafb; }
        .stat-label { font-size: 8px; text-transform: uppercase; color: #6b7280; }
        .stat-value { font-size: 14px; font-weight: bold; color: #111827; }

        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }
        .amt-cell { font-weight: bold; color: #ea580c; text-align: right; }
        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>PO Items Report</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: PO-ITEM-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">INTERNAL USE ONLY</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="center"><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</td>
                    <td align="right"><strong>Records:</strong> {{ $items->count() }}</td>
                </tr>
            </table>
        </div>

        {{-- Executive Summary (Calculated from current dataset) --}}
        <table class="stats-table">
            <tr>
                <td width="33%">
                    <div class="stat-box">
                        <div class="stat-label">Total Qty</div>
                        <div class="stat-value">{{ number_format($items->sum('quantity_ordered')) }}</div>
                    </div>
                </td>
                <td width="33%">
                    <div class="stat-box">
                        <div class="stat-label">Total Value (KES)</div>
                        <div class="stat-value" style="color: #ea580c;">{{ number_format($items->sum('total_cost'), 2) }}</div>
                    </div>
                </td>
                <td width="33%">
                    <div class="stat-box">
                        <div class="stat-label">Unique Products</div>
                        <div class="stat-value">{{ $items->unique('product_id')->count() }}</div>
                    </div>
                </td>
            </tr>
        </table>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="10%">Date</th>
                    <th width="12%">PO Ref</th>
                    <th width="15%">Supplier</th>
                    <th width="12%">Store</th>
                    <th width="20%">Product</th>
                    <th width="10%">SKU</th>
                    <th width="8%" style="text-align: right;">Qty</th>
                    <th width="13%" style="text-align: right;">Total Cost</th>
                </tr>
            </thead>
            <tbody>
                @foreach($items as $item)
                    <tr>
                        <td>{{ $item->purchaseOrder->order_date->format('d M Y') }}</td>
                        <td style="font-family: monospace;">{{ $item->purchaseOrder->po_number }}</td>
                        <td>{{ $item->purchaseOrder->supplier->name ?? '-' }}</td>
                        <td>{{ $item->purchaseOrder->store->name ?? '-' }}</td>
                        <td>{{ $item->product->name }}</td>
                        <td>{{ $item->product->sku }}</td>
                        <td align="right">{{ $item->quantity_ordered }}</td>
                        <td class="amt-cell">{{ number_format($item->total_cost, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </main>
</body>
</html>
