<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock Movement Items Report</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* Header & Footer Fixed Positioning */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        /* Typography & Layout */
        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        /* Info Box */
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        /* Table Styling */
        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        /* Status & Highlights */
        .ref-cell { font-family: monospace; font-weight: bold; color: #2d3748; }
        .status-sent { color: #1e40af; font-weight: bold; }
        .status-received { color: #15803d; font-weight: bold; }
        .status-draft { color: #6b7280; font-style: italic; }

        .qty-cell { font-weight: bold; color: #ea580c; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">123 Industrial Area, Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>Stock Movement Report</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: MOVEMENT-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="center">
                        @if(isset($date_from) || isset($date_to))
                            <strong>Period:</strong> {{ $date_from ?? 'Start' }} to {{ $date_to ?? 'Now' }}
                        @else
                            <strong>Period:</strong> All Time
                        @endif
                    </td>
                    <td align="right"><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="10%">Date</th>
                    <th width="12%">Transfer Ref</th>
                    <th width="8%">Status</th>
                    <th width="20%">Product Name</th>
                    <th width="10%">SKU</th>
                    <th width="15%">From Store</th>
                    <th width="15%">To Store</th>
                    <th width="10%" style="text-align: right;">Qty</th>
                </tr>
            </thead>
            <tbody>
                @foreach($items as $item)
                    <tr>
                        <td>{{ optional($item->stockTransfer->transfer_date)->format('d M Y') }}</td>
                        <td class="ref-cell">{{ $item->stockTransfer->reference ?? '-' }}</td>
                        <td>
                            @php $status = $item->stockTransfer->status ?? 'draft'; @endphp
                            @if($status === 'sent') <span class="status-sent">SENT</span>
                            @elseif($status === 'received') <span class="status-received">RCVD</span>
                            @else <span class="status-draft">{{ strtoupper(substr($status, 0, 4)) }}</span> @endif
                        </td>
                        <td>{{ $item->product->name ?? 'N/A' }}</td>
                        <td>{{ $item->product->sku ?? '-' }}</td>
                        <td>{{ $item->stockTransfer->sourceStore->name ?? '-' }}</td>
                        <td>{{ $item->stockTransfer->destinationStore->name ?? '-' }}</td>
                        <td align="right" class="qty-cell">{{ $item->quantity }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Items Moved:</strong> {{ number_format($items->sum('quantity')) }} &nbsp;|&nbsp; <strong>Total Records:</strong> {{ $items->count() }}
        </div>
    </main>
</body>
</html>
