<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Adjustment Requests Export</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* Fixed Header/Footer */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        /* Typography & Layout */
        .header-table, .meta-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        .meta-table td { vertical-align: top; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        /* Audit Box */
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        /* Data Table */
        .data-table th { background: #ea580c; color: #fff; font-weight: bold; text-transform: uppercase; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        /* Specific Status Colors */
        .st-approved { color: #15803d; font-weight: bold; }
        .st-rejected { color: #991b1b; font-weight: bold; }
        .st-pending { color: #b45309; font-weight: bold; }
        .st-draft { color: #4b5563; font-style: italic; }

        .qty-in { color: #15803d; font-weight: bold; }
        .qty-out { color: #b91c1c; font-weight: bold; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">
                        123 Industrial Area, Enterprise Road<br>
                        Nairobi, Kenya 00100<br>
                        support@alphalogistics.com | +254 700 000 000
                    </div>
                </td>
                <td width="40%" align="right">
                    <h1>Adjustments Report</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">
                        Ref: ADJ-EXP-{{ now()->timestamp }}
                    </div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL DOCUMENT</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table class="meta-table">
                <tr>
                    <td width="25%"><strong>Generated By:</strong><br> {{ auth()->user()->name ?? 'System User' }}</td>
                    <td width="25%"><strong>Role:</strong><br> {{ auth()->user()->role->label ?? 'N/A' }}</td>
                    <td width="25%"><strong>Store:</strong><br> {{ auth()->user()->store->name ?? 'Head Office' }}</td>
                    <td width="25%" align="right"><strong>Date:</strong><br> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="4%">#</th>
                    <th width="6%">Type</th>
                    <th width="12%">Store</th>
                    <th width="20%">Product / SKU</th>
                    <th width="8%" style="text-align: right;">Qty</th>
                    <th width="12%">Reason</th>
                    <th width="10%">Status</th>
                    <th width="12%">Requested By</th>
                    <th width="10%">Date</th>
                    <th width="6%">ID</th>
                </tr>
            </thead>
            <tbody>
                @foreach($requests as $req)
                    <tr>
                        <td align="center">{{ $loop->iteration }}</td>
                        <td>
                            @if($req->type === 'in') <span class="qty-in">IN (+)</span>
                            @else <span class="qty-out">OUT (-)</span> @endif
                        </td>
                        <td>{{ $req->store->name ?? '—' }}</td>
                        <td>
                            <strong>{{ $req->product->name ?? '—' }}</strong><br>
                            <span style="color:#666; font-size:8px;">{{ $req->product->sku ?? '' }}</span>
                        </td>
                        <td align="right" style="font-family:monospace; font-weight:bold;">
                            {{ number_format($req->quantity) }}
                        </td>
                        <td>{{ $req->reason->name ?? '—' }}</td>
                        <td>
                            @if($req->status === 'approved') <span class="st-approved">Approved</span>
                            @elseif($req->status === 'rejected') <span class="st-rejected">Rejected</span>
                            @elseif($req->status === 'draft') <span class="st-draft">Draft</span>
                            @else <span class="st-pending">Pending</span> @endif
                        </td>
                        <td>{{ $req->requester->name ?? 'System' }}</td>
                        <td>{{ $req->created_at->format('d M Y') }}</td>
                        <td align="center" style="font-size:8px; color:#777;">#{{ $req->id }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Records:</strong> {{ count($requests) }}
        </div>
    </main>
</body>
</html>
