<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Items Register</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* Fixed Header & Footer */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        /* Layout & Typography */
        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        /* Meta Box */
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        /* Data Table Styling */
        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        /* Specific Column Styles */
        .ref-cell { font-family: monospace; font-weight: bold; color: #2d3748; }
        .amount-cell { text-align: right; font-family: monospace; font-weight: bold; }
        .total-row { font-weight: bold; background-color: #eee !important; border-top: 2px solid #ea580c; color: #333; }

        .badge-retail { color: #0284c7; font-weight: bold; font-size: 8px; }
        .badge-wholesale { color: #7c2d12; font-weight: bold; font-size: 8px; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">123 Industrial Area, Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>Item Sales Report</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: ITM-REG-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="right"><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="12%">Date</th>
                    <th width="20%">Product</th>
                    <th width="8%">Type</th>
                    <th width="8%" class="amount-cell">Qty</th>
                    <th width="10%" class="amount-cell">Unit Price</th>
                    <th width="12%" class="amount-cell">Total</th>
                    <th width="12%">Ref</th>
                    <th width="10%">Store</th>
                    <th width="8%">Customer</th>
                </tr>
            </thead>
            <tbody>
                @foreach($items as $item)
                    <tr>
                        <td>{{ $item->sale->created_at->format('d M Y') }}</td>
                        <td>{{ $item->product->name ?? 'Unknown' }}</td>
                        <td>
                            <span class="{{ $item->price_category === 'retail' ? 'badge-retail' : 'badge-wholesale' }}">
                                {{ strtoupper(substr($item->price_category, 0, 4)) }}
                            </span>
                        </td>
                        <td class="amount-cell">{{ $item->quantity }}</td>
                        <td class="amount-cell">{{ number_format($item->unit_price, 2) }}</td>
                        <td class="amount-cell" style="color: #ea580c;">{{ number_format($item->total_price, 2) }}</td>
                        <td class="ref-cell">{{ $item->sale->reference_no }}</td>
                        <td>{{ $item->sale->store->name ?? '-' }}</td>
                        <td>{{ $item->sale->customer->name ?? 'Walk-in' }}</td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td colspan="3" align="right">TOTALS:</td>
                    <td class="amount-cell">{{ number_format($items->sum('quantity')) }}</td>
                    <td></td>
                    <td class="amount-cell">{{ number_format($items->sum('total_price'), 2) }}</td>
                    <td colspan="3"></td>
                </tr>
            </tfoot>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Records:</strong> {{ $items->count() }} &nbsp;|&nbsp;
            <strong>Avg Unit Price:</strong> {{ number_format($items->avg('unit_price'), 2) }}
        </div>
    </main>
</body>
</html>
