<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Debtors Master List</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* HEADER & FOOTER */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 85px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; color: #777; padding-top: 5px; }

        /* TYPOGRAPHY */
        .company-name { font-size: 15px; font-weight: bold; color: #111; text-transform: uppercase; }
        .company-details { font-size: 9px; color: #555; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .report-meta { font-size: 9px; color: #555; text-align: right; margin-top: 2px; }

        /* LOGO */
        .logo-img { max-height: 50px; width: auto; margin-bottom: 5px; }

        /* STATS & DATA TABLES */
        .stats-table { width: 100%; margin-bottom: 20px; }
        .stat-card-cell { width: 33.33%; padding: 5px; vertical-align: top; }
        .stat-card { border: 1px solid #e5e7eb; padding: 10px; border-radius: 4px; background: #fff; }
        .stat-title { font-size: 8px; text-transform: uppercase; color: #6b7280; font-weight: bold; letter-spacing: 0.5px; }
        .stat-value { font-size: 14px; font-weight: bold; color: #111; margin-top: 4px; }

        .meta-box {
            background-color: #fff7ed;
            border: 1px solid #fed7aa;
            padding: 8px;
            margin-bottom: 15px;
        }
        .meta-box strong { color: #ea580c; }
        .meta-table td { vertical-align: top; }

        .card-alert { background: #fff1f2; border-color: #fecaca; }
        .text-alert { color: #be123c; }
        .card-info { background: #eff6ff; border-color: #bfdbfe; }
        .text-info { color: #1d4ed8; }

        table { width: 100%; border-collapse: collapse; }
        .data-table th { background: #ea580c; color: #fff; padding: 7px 5px; border: 1px solid #c2410c; text-align: left; text-transform: uppercase; font-size: 8px; }
        .data-table td { border: 1px solid #e2e8f0; padding: 6px 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        .text-right { text-align: right; }
        .amount { font-family: monospace; font-weight: bold; font-size: 10px; }
        .badge { padding: 2px 4px; border-radius: 3px; font-size: 7px; font-weight: bold; text-transform: uppercase; }
        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>

        <table width="100%">
            <tr>
                <td width="15%" valign="top">
                    @if(isset($company) && $company->logo_path)
                        <img src="{{ public_path('storage/' . $company->logo_path) }}" class="logo-img">
                    @endif
                </td>
                <td width="45%" valign="top">
                    <div class="company-name">
                        {{ $company->name ?? $store->name ?? 'Alpha Logistics Systems' }}
                    </div>
                    <div class="company-details">
                        {{ $company->address ?? $store->address ?? 'Address Not Set' }}<br>
                        {{ $company->city ?? $store->city ?? 'City Not Set' }}
                        @if(!empty($company->phone) || !empty($store->phone)) | Tel: {{ $company->phone ?? $store->phone }} @endif
                        @if(!empty($company->email) || !empty($store->email)) | Email: {{ $company->email ?? $store->email }} @endif
                    </div>
                </td>
                <td width="40%" align="right" valign="top">
                    <h1>Debtors List</h1>
                    <div class="report-meta">Date: {{ now()->format('d M Y, h:i A') }}</div>
                    <div class="report-meta">Generated By: {{ auth()->user()->name ?? 'System' }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">{{ $store->name ?? 'Alpha Logistics' }}</td>
                <td align="center" width="33%">CONFIDENTIAL FINANCIAL REPORT</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table class="meta-table">
                <tr>
                    <td width="25%">
                        <strong>Generated By:</strong><br>
                        {{ auth()->user()->name ?? 'System User' }}
                    </td>
                    <td width="25%">
                        <strong>Role / Position:</strong><br>
                       {{ ucfirst(auth()->user()->roles->first()?->name ?? auth()->user()->role?->name ?? 'Standard User') }}
                    </td>
                    <td width="25%">
                        <strong>Store / Branch:</strong><br>
                        {{ auth()->user()->store->name ?? 'Head Office' }}
                    </td>
                    <td width="25%" align="right">
                        <strong>Generated On:</strong><br>
                        {{ now()->format('d M Y, h:i A') }}
                    </td>
                </tr>
            </table>
        </div>
        <table class="stats-table">
            <tr>
                <td class="stat-card-cell">
                    <div class="stat-card card-alert">
                        <div class="stat-title text-alert">Total Outstanding</div>
                        <div class="stat-value text-alert">{{ number_format($stats['total_outstanding'], 2) }}</div>
                    </div>
                </td>
                <td class="stat-card-cell">
                    <div class="stat-card card-info">
                        <div class="stat-title text-info">Active Debtors</div>
                        <div class="stat-value text-info">{{ number_format($stats['debtors_count']) }}</div>
                    </div>
                </td>
                <td class="stat-card-cell">
                    <div class="stat-card">
                        <div class="stat-title">Avg. Debt per Customer</div>
                        <div class="stat-value">{{ number_format($stats['avg_debt'], 2) }}</div>
                    </div>
                </td>
            </tr>
        </table>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="25%">Customer Name</th>
                    <th width="15%">Store</th> <th width="10%">Phone</th>
                    <th width="15%" class="text-right">Credit Limit</th>
                    <th width="15%" class="text-right">Total Debt</th>
                    <th width="8%" class="text-right">Usage</th>
                    <th width="7%">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($debtors as $c)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td style="font-weight: bold;">{{ $c->name }}</td>
                    <td>{{ $c->store->name ?? 'Global' }}</td>
                    <td>{{ $c->phone ?? $c->number ?? '-' }}</td>
                    <td class="text-right amount">{{ number_format($c->credit_limit, 2) }}</td>
                    <td class="text-right amount" style="color: #dc2626;">{{ number_format($c->debts_sum_balance, 2) }}</td>
                    <td class="text-right">
                        @php $usage = $c->credit_limit > 0 ? ($c->debts_sum_balance / $c->credit_limit) * 100 : 0; @endphp
                        {{ number_format($usage, 0) }}%
                    </td>
                    <td>
                        @if($usage > 100) <span class="badge" style="background: #fee2e2; color: #b91c1c;">OVER</span>
                        @elseif($usage > 80) <span class="badge" style="background: #ffedd5; color: #c2410c;">HIGH</span>
                        @else <span class="badge" style="background: #dcfce7; color: #15803d;">OK</span> @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr style="background: #eee; font-weight: bold;">
                    <td colspan="5" align="right" style="padding-right: 10px;">TOTAL OUTSTANDING:</td>
                    <td class="text-right amount" style="color: #ea580c; border-top: 2px solid #ea580c;">
                        {{ number_format($stats['total_outstanding'], 2) }}
                    </td>
                    <td colspan="2"></td>
                </tr>
            </tfoot>
        </table>
    </main>
</body>
</html>
