<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Customer Master List</title>
    <style>
        /** DOMPDF COMPATIBILITY SETTINGS */
        @page {
            margin: 100px 25px 60px 25px; /* Top, Right, Bottom, Left */
        }

        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            color: #333;
            line-height: 1.4;
        }

        /* --- HEADER & FOOTER (Fixed positions) --- */
        header {
            position: fixed;
            top: -80px;
            left: 0px;
            right: 0px;
            height: 80px;
            border-bottom: 2px solid #ea580c; /* Orange accent */
        }

        footer {
            position: fixed;
            bottom: -40px;
            left: 0px;
            right: 0px;
            height: 30px;
            border-top: 1px solid #ea580c;
            text-align: center;
            font-size: 8px;
            color: #777;
            padding-top: 5px;
        }

        /* --- LAYOUT TABLES --- */
        .header-table, .meta-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        .header-table td {
            vertical-align: middle;
        }

        /* --- TYPOGRAPHY --- */
        h1 {
            font-size: 18px;
            color: #ea580c; /* System Orange */
            margin: 0;
            text-transform: uppercase;
            font-weight: bold;
            text-align: right;
        }

        .company-name {
            font-size: 14px;
            font-weight: bold;
            color: #111;
        }

        .company-details {
            font-size: 9px;
            color: #555;
        }

        /* --- AUDIT INFO BOX --- */
        .meta-box {
            background-color: #fff7ed; /* Very Light Orange */
            border: 1px solid #fed7aa; /* Light Orange Border */
            padding: 8px;
            margin-bottom: 15px;
        }

        .meta-box strong {
            color: #ea580c;
        }

        /* --- DATA TABLE --- */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .data-table th {
            background-color: #ea580c; /* System Orange */
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            padding: 8px 5px;
            font-size: 9px;
            border: 1px solid #c2410c;
            text-align: left;
        }

        .data-table td {
            border: 1px solid #e2e8f0;
            padding: 6px 5px;
            font-size: 9px;
            color: #2d3748;
            vertical-align: middle;
        }

        /* Warm/Orange Zebra Striping */
        .data-table tr:nth-child(even) {
            background-color: #ffedd5;
        }

        /* Financial Column Styling */
        .credit-cell {
            font-family: 'Courier New', monospace;
            font-weight: bold;
            text-align: right;
            color: #2d3748;
        }

        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>

    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div class="company-details">
                        123 Industrial Area, Enterprise Road<br>
                        Nairobi, Kenya 00100<br>
                        support@alphalogistics.com | +254 700 000 000
                    </div>
                </td>
                <td width="40%" align="right">
                    <h1>Customer List</h1>
                    <div class="company-details" style="margin-top: 5px;">
                        Ref: CUST-EXP-{{ now()->timestamp }}
                    </div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL DOCUMENT</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table class="meta-table">
                <tr>
                    <td width="25%">
                        <strong>Generated By:</strong><br>
                        {{ auth()->user()->name ?? 'System User' }}
                    </td>
                    <td width="25%">
                        <strong>Role / Position:</strong><br>
                        {{ auth()->user()->role->label ?? 'N/A' }}
                    </td>
                    <td width="25%">
                        <strong>Store / Branch:</strong><br>
                        {{ auth()->user()->store->name ?? 'Head Office' }}
                    </td>
                    <td width="25%" align="right">
                        <strong>Generated On:</strong><br>
                        {{ now()->format('d M Y, h:i A') }}
                    </td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="5%">#</th>
                    <th width="25%">Customer Name</th>
                    <th width="15%">Contact Number</th>
                    <th width="25%">Email Address</th>
                    <th width="20%" style="text-align: right;">Credit Limit</th>
                    <th width="10%">Registered</th>
                </tr>
            </thead>
            <tbody>
                @foreach($customers as $customer)
                    <tr>
                        <td align="center">{{ $loop->iteration }}</td>
                        <td style="font-weight: bold;">{{ $customer->name ?? '—' }}</td>
                        <td>{{ $customer->number ?? '—' }}</td>
                        <td>{{ $customer->email ?? '—' }}</td>

                        {{-- 🟢 Credit Limit Formatted for Clarity --}}
                        <td class="credit-cell">
                            KSH {{ number_format($customer->credit_limit ?? 0.00, 2) }}
                        </td>

                        <td>{{ $customer->created_at ? $customer->created_at->format('d M Y') : '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Customers Listed:</strong> {{ count($customers) }}
        </div>
    </main>

</body>
</html>
