<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quotations Register</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* Fixed Header & Footer */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        /* Layout & Typography */
        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        /* Meta Box */
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        /* Data Table Styling */
        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        /* Specific Column Styles */
        .ref-cell { font-family: monospace; font-weight: bold; color: #2d3748; }
        .amount-cell { text-align: right; font-family: monospace; font-weight: bold; }
        .total-row { font-weight: bold; background-color: #eee !important; border-top: 2px solid #ea580c; }

        /* Status Colors */
        .status-sent { color: #1e40af; font-weight: bold; }
        .status-accepted { color: #15803d; font-weight: bold; }
        .status-rejected { color: #dc2626; font-weight: bold; }
        .status-expired { color: #c2410c; font-weight: bold; }
        .status-draft { color: #6b7280; font-style: italic; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">123 Industrial Area, Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>Quotations Register</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: QT-REG-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="right"><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="10%">Date</th>
                    <th width="12%">Quote #</th>
                    <th width="20%">Customer</th>
                    <th width="15%">Store</th>
                    <th width="5%" style="text-align: right;">Items</th>
                    <th width="12%">Valid Until</th>
                    <th width="14%" style="text-align: right;">Total Amount</th>
                    <th width="12%">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($quotations as $quote)
                    <tr>
                        <td>{{ $quote->quotation_date->format('d M Y') }}</td>
                        <td class="ref-cell">{{ $quote->quotation_number }}</td>
                        <td>{{ $quote->customer->name ?? 'Unknown Customer' }}</td>
                        <td>{{ $quote->store->name ?? '-' }}</td>
                        <td align="right">{{ $quote->items_count }}</td>
                        <td>{{ $quote->valid_until ? $quote->valid_until->format('d M Y') : '-' }}</td>
                        <td class="amount-cell">{{ number_format($quote->total_amount, 2) }}</td>
                        <td>
                            @php $status = strtolower($quote->status); @endphp
                            @if($status === 'accepted') <span class="status-accepted">ACCEPTED</span>
                            @elseif($status === 'sent') <span class="status-sent">SENT</span>
                            @elseif($status === 'rejected') <span class="status-rejected">REJECTED</span>
                            @elseif($status === 'expired') <span class="status-expired">EXPIRED</span>
                            @else <span class="status-draft">{{ strtoupper($status) }}</span> @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td colspan="6" align="right">TOTAL POTENTIAL VALUE:</td>
                    <td class="amount-cell">{{ number_format($quotations->sum('total_amount'), 2) }}</td>
                    <td></td>
                </tr>
            </tfoot>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Records:</strong> {{ $quotations->count() }} &nbsp;|&nbsp;
            <strong>Avg Quote Value:</strong> {{ $quotations->count() > 0 ? number_format($quotations->avg('total_amount'), 2) : '0.00' }}
        </div>
    </main>
</body>
</html>
