<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Quotation {{ $quotation->quotation_number }}</title>
    <style>
        @page { margin: 100px 25px 100px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 10px; color: #333; line-height: 1.4; }

        /* HEADER & FOOTER */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -60px; left: 0px; right: 0px; height: 50px; border-top: 1px solid #ea580c; font-size: 8px; color: #777; padding-top: 10px; }

        /* TABLES */
        table { width: 100%; border-collapse: collapse; }
        .header-table td { vertical-align: top; }

        .info-table { width: 100%; margin-bottom: 15px; border: 1px solid #e2e8f0; }
        .info-table th { background: #f8fafc; color: #4a5568; padding: 6px; text-align: left; font-size: 9px; text-transform: uppercase; border-bottom: 1px solid #e2e8f0; }
        .info-table td { padding: 6px; border-bottom: 1px solid #eee; }
        .info-table tr:last-child td { border-bottom: none; }

        /* TYPOGRAPHY */
        h1 { font-size: 22px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; color: #111; }
        .section-title { font-size: 11px; font-weight: bold; color: #ea580c; border-bottom: 1px solid #e2e8f0; margin: 15px 0 8px 0; text-transform: uppercase; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .font-bold { font-weight: bold; }
        .text-red { color: #dc2626; }
        .text-green { color: #16a34a; }

        /* BADGES */
        .badge { padding: 3px 8px; border-radius: 4px; font-weight: bold; font-size: 9px; text-transform: uppercase; display: inline-block; }
        .badge-draft { background: #f3f4f6; color: #374151; border: 1px solid #d1d5db; }
        .badge-sent { background: #dbeafe; color: #1e40af; border: 1px solid #93c5fd; }
        .badge-accepted { background: #dcfce7; color: #166534; border: 1px solid #86efac; }
        .badge-rejected { background: #fee2e2; color: #991b1b; border: 1px solid #fca5a5; }
        .badge-expired { background: #ffedd5; color: #9a3412; border: 1px solid #fed7aa; }

        /* AUDIT GRID */
        .audit-grid { width: 100%; border: 1px solid #eee; margin-top: 10px; }
        .audit-grid td { width: 33%; vertical-align: top; padding: 8px; border-right: 1px solid #eee; }
        .audit-grid td:last-child { border-right: none; }
        .audit-label { font-size: 8px; text-transform: uppercase; color: #777; margin-bottom: 2px; }
        .audit-val { font-weight: bold; font-size: 10px; }
        .audit-date { font-size: 8px; color: #555; }

        .watermark {
            position: fixed; top: 30%; left: 10%; width: 80%; text-align: center;
            font-size: 100px; color: rgba(200, 200, 200, 0.1); transform: rotate(-45deg);
            z-index: -1000; font-weight: bold; text-transform: uppercase;
        }
    </style>
</head>
<body>

    @if($quotation->status === 'draft')
        <div class="watermark">DRAFT</div>
    @elseif($quotation->status === 'rejected')
        <div class="watermark" style="color: rgba(220, 38, 38, 0.05);">REJECTED</div>
    @elseif($quotation->status === 'expired')
        <div class="watermark" style="color: rgba(234, 88, 12, 0.05);">EXPIRED</div>
    @endif

    <header>
        <table class="header-table">
            <tr>
                <td width="50%">
                    <div class="company-name">{{ strtoupper($quotation->store->name ?? 'Store Name') }}</div>
                    <div style="font-size: 9px; color: #555; margin-top: 4px;">
                        {{ $quotation->store->address ?? '123 Enterprise Road' }}<br>
                        {{ $quotation->store->city ?? 'Nairobi' }}, Kenya<br>
                        Phone: {{ $quotation->store->phone ?? '+254 ...' }}<br>
                        Email: {{ $quotation->store->email ?? 'info@store.com' }}
                    </div>
                </td>
                <td width="50%" align="right">
                    <h1>Quotation</h1>
                    <div style="font-size: 11px; margin-top: 5px;"># {{ $quotation->quotation_number }}</div>
                    <div style="margin-top: 5px;">
                        <span class="badge badge-{{ $quotation->status }}">{{ $quotation->status }}</span>
                    </div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td width="33%" align="left">
                    Generated by: {{ Auth::user()->name }}<br>
                    Printed: {{ now()->format('d M Y, h:i A') }}
                </td>
                <td width="33%" align="center">
                    This quotation is valid until the date specified.
                </td>
                <td width="33%" align="right">
                    Page <span class="page-number"></span>
                </td>
            </tr>
        </table>
    </footer>

    <main>
        <table class="w-full" style="margin-bottom: 20px;">
            <tr>
                <td width="50%" valign="top" style="background: #f9f9f9; padding: 10px; border: 1px solid #eee;">
                    <div class="audit-label">Quotation For</div>
                    <div style="font-size: 11px; font-weight: bold;">{{ $quotation->customer->name }}</div>
                    @if($quotation->customer->phone)
                        <div>Tel: {{ $quotation->customer->phone }}</div>
                    @endif
                    @if($quotation->customer->email)
                        <div>Email: {{ $quotation->customer->email }}</div>
                    @endif
                    <div style="margin-top: 5px; font-size: 9px; color: #555;">
                        Customer ID: #{{ $quotation->customer_id }}
                    </div>
                </td>
                <td width="5%" style="border:none;"></td>
                <td width="45%" valign="top">
                    <table class="info-table" style="margin: 0;">
                        <tr>
                            <th width="40%">Quote Date</th>
                            <td align="right">{{ $quotation->quotation_date->format('d M Y') }}</td>
                        </tr>
                        <tr>
                            <th>Valid Until</th>
                            <td align="right" style="color: #ea580c; font-weight: bold;">
                                {{ $quotation->valid_until ? $quotation->valid_until->format('d M Y') : 'N/A' }}
                            </td>
                        </tr>
                        <tr>
                            <th>Currency</th>
                            <td align="right">KES</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

        <div class="section-title">Item Details</div>
        <table class="info-table">
            <thead>
                <tr>
                    <th width="5%" class="text-center">#</th>
                    <th width="45%">Description / Product</th>
                    <th width="15%">SKU</th>
                    <th width="10%" class="text-center">Qty</th>
                    <th width="12%" class="text-right">Unit Price</th>
                    <th width="13%" class="text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach($quotation->items as $item)
                <tr>
                    <td align="center">{{ $loop->iteration }}</td>
                    <td>
                        <span class="font-bold">{{ $item->product->name }}</span>
                    </td>
                    <td style="font-family: monospace; color: #555;">{{ $item->product->sku }}</td>
                    <td align="center">{{ $item->quantity }}</td>
                    <td align="right">{{ number_format($item->unit_price, 2) }}</td>
                    <td align="right" class="font-bold">{{ number_format($item->sub_total, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <table width="100%">
            <tr>
                <td width="55%" valign="top" style="padding-right: 20px;">
                    @if($quotation->notes)
                        <div class="section-title">Notes / Terms</div>
                        <div style="border: 1px dashed #ccc; padding: 8px; font-style: italic; background: #fff; font-size: 9px;">
                            {{ $quotation->notes }}
                        </div>
                    @else
                        <div class="section-title">Terms</div>
                        <div style="font-size: 9px; color: #555;">
                            1. Goods once sold are not returnable.<br>
                            2. Prices valid until expiry date.<br>
                            3. Subject to availability.
                        </div>
                    @endif
                </td>

                <td width="45%" valign="top">
                    <table class="info-table">
                        <tr>
                            <td class="text-right font-bold">Subtotal</td>
                            <td align="right" width="40%">{{ number_format($quotation->sub_total, 2) }}</td>
                        </tr>
                        @if($quotation->discount_amount > 0)
                        <tr>
                            <td class="text-right">Discount</td>
                            <td align="right" class="text-red">({{ number_format($quotation->discount_amount, 2) }})</td>
                        </tr>
                        @endif
                        @if($quotation->tax_amount > 0)
                        <tr>
                            <td class="text-right">Tax / VAT</td>
                            <td align="right">{{ number_format($quotation->tax_amount, 2) }}</td>
                        </tr>
                        @endif
                        <tr style="background: #f1f5f9;">
                            <td class="text-right font-bold" style="font-size: 12px; padding: 10px;">TOTAL ESTIMATE</td>
                            <td align="right" class="font-bold" style="font-size: 12px; padding: 10px;">{{ number_format($quotation->total_amount, 2) }}</td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>

        <div class="section-title" style="margin-top: 30px;">System Audit Trail</div>
        <table class="audit-grid" cellspacing="0">
            <tr>
                <td>
                    <div class="audit-label">Prepared By</div>
                    <div class="audit-val">{{ $quotation->user->name ?? 'System' }}</div>
                    <div class="audit-date">{{ $quotation->created_at->format('d M Y, h:i A') }}</div>
                </td>

                <td>
                    <div class="audit-label">Last Updated</div>
                    <div class="audit-val">{{ $quotation->updated_at->diffForHumans() }}</div>
                    <div class="audit-date">{{ $quotation->updated_at->format('d M Y, h:i A') }}</div>
                </td>

                <td>
                    <div class="audit-label">Status</div>
                    <div class="audit-val">{{ strtoupper($quotation->status) }}</div>
                </td>
            </tr>
        </table>

        <div style="margin-top: 40px; border-top: 1px dashed #ccc; padding-top: 10px;">
             <table width="100%">
                <tr>
                    <td width="50%">
                        <strong>Authorized Signature:</strong><br><br>
                        __________________________________
                    </td>
                    <td width="50%" align="right">
                        <strong>Client Acceptance:</strong><br><br>
                        __________________________________
                    </td>
                </tr>
            </table>
        </div>

    </main>
</body>
</html>
