<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Supplier Profile: {{ $supplier->name }}</title>
    <style>
        /** DOMPDF COMPATIBILITY SETTINGS */
        @page {
            margin: 100px 25px 60px 25px;
        }

        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            color: #333;
            line-height: 1.5;
        }

        /* --- HEADER & FOOTER --- */
        header {
            position: fixed;
            top: -80px;
            left: 0px;
            right: 0px;
            height: 80px;
            border-bottom: 2px solid #ea580c; /* Orange accent */
        }

        footer {
            position: fixed;
            bottom: -40px;
            left: 0px;
            right: 0px;
            height: 30px;
            border-top: 1px solid #ea580c;
            text-align: center;
            font-size: 8px;
            color: #777;
            padding-top: 5px;
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
        }

        .company-name {
            font-size: 14px;
            font-weight: bold;
            color: #111;
        }

        .company-details {
            font-size: 9px;
            color: #555;
        }

        h1 {
            font-size: 18px;
            color: #ea580c;
            margin: 0;
            text-transform: uppercase;
            font-weight: bold;
            text-align: right;
        }

        /* --- AUDIT META BOX --- */
        .meta-box {
            background-color: #fff7ed;
            border: 1px solid #fed7aa;
            padding: 10px;
            margin-bottom: 20px;
            font-size: 9px;
        }

        .meta-table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta-table td {
            vertical-align: top;
        }

        /* --- SECTION STYLING --- */
        .section-title {
            font-size: 12px;
            font-weight: bold;
            color: #ea580c;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 5px;
            margin-top: 20px;
            margin-bottom: 10px;
            text-transform: uppercase;
        }

        /* --- DATA TABLES --- */
        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        .info-table th {
            text-align: left;
            width: 25%;
            padding: 6px;
            background-color: #f8fafc;
            color: #4a5568;
            border: 1px solid #e2e8f0;
            font-weight: bold;
            font-size: 9px;
        }

        .info-table td {
            padding: 6px;
            border: 1px solid #e2e8f0;
            color: #2d3748;
            font-size: 10px;
        }

        /* Status Badges */
        .status-badge-active {
            color: #15803d;
            font-weight: bold;
            background-color: #dcfce7;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 9px;
        }

        .status-badge-inactive {
            color: #b91c1c;
            font-weight: bold;
            background-color: #fee2e2;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 9px;
        }

        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>

    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div class="company-details">
                        123 Industrial Area, Enterprise Road<br>
                        Nairobi, Kenya 00100<br>
                        support@alphalogistics.com | +254 700 000 000
                    </div>
                </td>
                <td width="40%" align="right">
                    <h1>Supplier Profile</h1>
                    <div class="company-details" style="margin-top: 5px;">
                        System ID: #{{ $supplier->id }}
                    </div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL DOCUMENT</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table class="meta-table">
                <tr>
                    <td width="33%">
                        <strong>Generated By:</strong><br> {{ auth()->user()->name ?? 'System User' }}
                    </td>
                    <td width="33%">
                        <strong>Role:</strong><br> {{ auth()->user()->role->label ?? 'N/A' }}
                    </td>
                    <td width="33%" align="right">
                        <strong>Date:</strong><br> {{ now()->format('d M Y, h:i A') }}
                    </td>
                </tr>
            </table>
        </div>

        <div class="section-title">Supplier Identity</div>
        <table class="info-table">
            <tr>
                <th>Supplier Name</th>
                <td style="font-size: 12px; font-weight: bold;">{{ $supplier->name }}</td>
            </tr>
            <tr>
                <th>System Slug</th>
                <td style="font-family: monospace; color: #666;">{{ $supplier->slug ?? '—' }}</td>
            </tr>
            <tr>
                <th>Account Status</th>
                <td>
                    @if($supplier->is_active)
                        <span class="status-badge-active">ACTIVE</span>
                    @else
                        <span class="status-badge-inactive">INACTIVE</span>
                    @endif
                </td>
            </tr>
        </table>

        <div class="section-title">Contact Information</div>
        <table class="info-table">
            <tr>
                <th>Contact Person</th>
                <td>{{ $supplier->contact_person ?? '—' }}</td>
            </tr>
            <tr>
                <th>Email Address</th>
                <td>{{ $supplier->email ?? '—' }}</td>
            </tr>
            <tr>
                <th>Phone Number</th>
                <td>{{ $supplier->phone ?? '—' }}</td>
            </tr>
            <tr>
                <th>Physical Address</th>
                <td>{!! nl2br(e($supplier->address ?? 'No address provided')) !!}</td>
            </tr>
        </table>

        <div class="section-title">System History</div>
        <table class="info-table">
            <tr>
                <th>Registered On</th>
                <td>{{ $supplier->created_at ? $supplier->created_at->format('d F Y') : '—' }} <span style="color:#777; font-size:8px;">({{ $supplier->created_at?->format('H:i:s') }})</span></td>
            </tr>
            <tr>
                <th>Last Updated</th>
                <td>{{ $supplier->updated_at ? $supplier->updated_at->format('d F Y') : '—' }} <span style="color:#777; font-size:8px;">({{ $supplier->updated_at?->format('H:i:s') }})</span></td>
            </tr>
        </table>

    </main>
</body>
</html>
