<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoices Register</title>
    <style>
        @page { margin: 100px 25px 60px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 9px; color: #333; line-height: 1.4; }

        /* Fixed Header & Footer */
        header { position: fixed; top: -80px; left: 0px; right: 0px; height: 80px; border-bottom: 2px solid #ea580c; }
        footer { position: fixed; bottom: -40px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ea580c; text-align: center; font-size: 8px; color: #777; padding-top: 5px; }

        /* Typography & Layout */
        .header-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        h1 { font-size: 18px; color: #ea580c; margin: 0; text-transform: uppercase; font-weight: bold; text-align: right; }
        .company-name { font-size: 14px; font-weight: bold; }

        /* Meta Box */
        .meta-box { background: #fff7ed; border: 1px solid #fed7aa; padding: 8px; margin-bottom: 15px; }
        .meta-box strong { color: #ea580c; }

        /* Data Table Styling */
        .data-table th { background: #ea580c; color: #fff; padding: 6px 4px; border: 1px solid #c2410c; text-align: left; font-size: 8px; text-transform: uppercase; }
        .data-table td { border: 1px solid #e2e8f0; padding: 5px; vertical-align: middle; }
        .data-table tr:nth-child(even) { background: #ffedd5; }

        /* Specific Column Styles */
        .ref-cell { font-family: monospace; font-weight: bold; color: #2d3748; }
        .amount-cell { text-align: right; font-family: monospace; }
        .total-row { font-weight: bold; background-color: #eee !important; border-top: 2px solid #ea580c; }

        /* Status Colors */
        .status-paid { color: #15803d; font-weight: bold; }
        .status-partial { color: #ca8a04; font-weight: bold; }
        .status-unpaid { color: #dc2626; font-weight: bold; }
        .status-void { color: #6b7280; text-decoration: line-through; }

        .page-number:before { content: "Page " counter(page); }
    </style>
</head>
<body>
    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div style="font-size: 9px; color: #555;">123 Industrial Area, Nairobi, Kenya</div>
                </td>
                <td width="40%" align="right">
                    <h1>Invoices Register</h1>
                    <div style="font-size: 9px; color: #555; margin-top: 5px;">Ref: INV-REG-{{ now()->timestamp }}</div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table width="100%">
                <tr>
                    <td><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
                    <td align="right"><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="10%">Date</th>
                    <th width="12%">Invoice #</th>
                    <th width="20%">Customer</th>
                    <th width="15%">Store</th>
                    <th width="5%" style="text-align: right;">Items</th>
                    <th width="12%" style="text-align: right;">Total</th>
                    <th width="12%" style="text-align: right;">Paid</th>
                    <th width="14%">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($invoices as $inv)
                    <tr>
                        <td>{{ $inv->invoice_date->format('d M Y') }}</td>
                        <td class="ref-cell">{{ $inv->invoice_number }}</td>
                        <td>{{ $inv->customer->name ?? 'Walk-in Customer' }}</td>
                        <td>{{ $inv->store->name ?? '-' }}</td>
                        <td align="right">{{ $inv->items_count }}</td>
                        <td class="amount-cell">{{ number_format($inv->total_amount, 2) }}</td>
                        <td class="amount-cell">{{ number_format($inv->paid_amount, 2) }}</td>
                        <td>
                            @php $status = strtolower($inv->status); @endphp
                            @if($status === 'paid') <span class="status-paid">PAID</span>
                            @elseif($status === 'partial') <span class="status-partial">PARTIAL</span>
                            @elseif($status === 'unpaid') <span class="status-unpaid">UNPAID</span>
                            @elseif($status === 'void') <span class="status-void">VOID</span>
                            @else {{ strtoupper($status) }} @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="total-row">
                    <td colspan="5" align="right">TOTALS:</td>
                    <td class="amount-cell">{{ number_format($invoices->sum('total_amount'), 2) }}</td>
                    <td class="amount-cell">{{ number_format($invoices->sum('paid_amount'), 2) }}</td>
                    <td></td>
                </tr>
            </tfoot>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777;">
            <strong>Total Records:</strong> {{ $invoices->count() }} &nbsp;|&nbsp;
            <strong>Outstanding Balance:</strong> {{ number_format($invoices->sum('total_amount') - $invoices->sum('paid_amount'), 2) }}
        </div>
    </main>
</body>
</html>
