<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Stock Receipts Register</title>
    <style>
        /** DOMPDF COMPATIBILITY SETTINGS */
        @page {
            margin: 100px 25px 60px 25px; /* Top, Right, Bottom, Left */
        }

        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 9px;
            color: #333;
            line-height: 1.4;
        }

        /* --- HEADER & FOOTER (Fixed positions) --- */
        header {
            position: fixed;
            top: -80px;
            left: 0px;
            right: 0px;
            height: 80px;
            border-bottom: 2px solid #ea580c; /* Orange accent */
        }

        footer {
            position: fixed;
            bottom: -40px;
            left: 0px;
            right: 0px;
            height: 30px;
            border-top: 1px solid #ea580c;
            text-align: center;
            font-size: 8px;
            color: #777;
            padding-top: 5px;
        }

        /* --- LAYOUT TABLES --- */
        .header-table, .meta-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        .header-table td {
            vertical-align: middle;
        }

        /* --- TYPOGRAPHY --- */
        h1 {
            font-size: 18px;
            color: #ea580c; /* System Orange */
            margin: 0;
            text-transform: uppercase;
            font-weight: bold;
            text-align: right;
        }

        .company-name {
            font-size: 14px;
            font-weight: bold;
            color: #111;
        }

        .company-details {
            font-size: 9px;
            color: #555;
        }

        /* --- AUDIT INFO BOX --- */
        .meta-box {
            background-color: #fff7ed;
            border: 1px solid #fed7aa;
            padding: 8px;
            margin-bottom: 15px;
        }

        .meta-box strong {
            color: #ea580c;
        }

        /* --- DATA TABLE --- */
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .data-table th {
            background-color: #ea580c; /* System Orange */
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            padding: 8px 5px;
            font-size: 8px;
            border: 1px solid #c2410c;
            text-align: left;
        }

        .data-table td {
            border: 1px solid #e2e8f0;
            padding: 6px 5px;
            font-size: 9px;
            color: #2d3748;
            vertical-align: middle;
        }

        /* Warm/Orange Zebra Striping */
        .data-table tr:nth-child(even) {
            background-color: #ffedd5;
        }

        /* Specific Cell Styles */
        .invoice-cell {
            font-family: 'Courier New', monospace;
            font-weight: bold;
            color: #2d3748;
        }

        .qty-cell {
            text-align: right;
            font-weight: bold;
            font-size: 10px;
        }

        /* Status Badges */
        .status-completed { color: #15803d; font-weight: bold; text-transform: uppercase; font-size: 8px; }
        .status-pending { color: #b45309; font-weight: bold; text-transform: uppercase; font-size: 8px; }

        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>

    <header>
        <table class="header-table">
            <tr>
                <td width="60%">
                    <div class="company-name">ALPHA LOGISTICS SYSTEMS</div>
                    <div class="company-details">
                        123 Industrial Area, Enterprise Road<br>
                        Nairobi, Kenya 00100<br>
                        support@alphalogistics.com | +254 700 000 000
                    </div>
                </td>
                <td width="40%" align="right">
                    <h1>Receipts Register</h1>
                    <div class="company-details" style="margin-top: 5px;">
                        Ref: GRN-EXP-{{ now()->timestamp }}
                    </div>
                </td>
            </tr>
        </table>
    </header>

    <footer>
        <table width="100%">
            <tr>
                <td align="left" width="33%">Generated via Alpha System</td>
                <td align="center" width="33%">CONFIDENTIAL DOCUMENT</td>
                <td align="right" width="33%"><span class="page-number"></span></td>
            </tr>
        </table>
    </footer>

    <main>
        <div class="meta-box">
            <table class="meta-table">
                <tr>
                    <td width="25%">
                        <strong>Generated By:</strong><br>
                        {{ auth()->user()->name ?? 'System User' }}
                    </td>
                    <td width="25%">
                        <strong>Role / Position:</strong><br>
                        {{ auth()->user()->role->label ?? 'N/A' }}
                    </td>
                    <td width="25%">
                        <strong>Store / Branch:</strong><br>
                        {{ auth()->user()->store->name ?? 'Head Office' }}
                    </td>
                    <td width="25%" align="right">
                        <strong>Generated On:</strong><br>
                        {{ now()->format('d M Y, h:i A') }}
                    </td>
                </tr>
            </table>
        </div>

        <table class="data-table">
            <thead>
                <tr>
                    <th width="4%">#</th>
                    <th width="12%">Invoice / Ref</th>
                    <th width="20%">Product Details</th>
                    <th width="15%">Supplier</th>
                    <th width="15%">Destination Store</th>
                    <th width="8%" style="text-align: right;">Qty</th>
                    <th width="8%">Status</th>
                    <th width="10%">Recorded By</th>
                    <th width="8%">Date</th>
                </tr>
            </thead>
            <tbody>
                @foreach($entries as $entry)
                    <tr>
                        <td align="center">{{ $loop->iteration }}</td>

                        <td class="invoice-cell">
                            {{ $entry->invoice_number ?? 'N/A' }}
                        </td>

                        <td>
                            <strong>{{ $entry->product->name ?? 'Unknown' }}</strong><br>
                            <span style="color:#666; font-size:8px;">SKU: {{ $entry->product->sku ?? '—' }}</span>
                        </td>

                        <td>{{ $entry->supplier->name ?? '—' }}</td>
                        <td>{{ $entry->store->name ?? '—' }}</td>

                        <td class="qty-cell">
                            {{ number_format($entry->quantity_received) }}
                        </td>

                        <td>
                            @if($entry->status === 'completed')
                                <span class="status-completed">Posted</span>
                            @else
                                <span class="status-pending">Pending</span>
                            @endif
                        </td>

                        <td>{{ $entry->user->name ?? 'System' }}</td>
                        <td>{{ $entry->created_at ? $entry->created_at->format('d M Y') : '—' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 20px; text-align: right; font-size: 9px; color: #777; border-top: 1px dashed #ea580c; padding-top: 5px;">
            <strong>Total Entries:</strong> {{ count($entries) }} &nbsp;|&nbsp;
            <strong>Total Volume:</strong> {{ number_format($entries->sum('quantity_received')) }} units
        </div>
    </main>

</body>
</html>
